// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hysmmutuoiymirqqpcct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5c21tdXR1b2l5bWlycXFwY2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTQxNDQsImV4cCI6MjA2OTk3MDE0NH0.hK2_2KznINgcr-7dMCbE0Qp4jrW3uighVqlXKhDPMH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
